title: Bitcoiners que Vivem de Alavancagem
description: Simulador de operações alavancadas em Bitcoin
theme: jekyll-theme-midnight

markdown: kramdown

plugins:
  - jekyll-feed

header_pages:
  - index.md
