title: Bitcoiners que Vivem de Alavancagem
description: Simulador de operações alavancadas em Bitcoin

# Tema GitHub Pages (escuro, estilo Slate)
remote_theme: pages-themes/slate@v0.2.0

plugins:
  - jekyll-remote-theme

header_pages:
  - index.md


url: "https://luizkaisa.github.io"
baseurl: "/Alavancagem"
# Opções genéricas usadas por alguns temas (não quebram nada se não forem usadas)
show_downloads: false
github:
  is_project_page: true
