title: Bitcoiners que Vivem de Alavancagem
description: Simulador de operações alavancadas em Bitcoin
theme: just-the-docs

color_scheme: light

markdown: kramdown

plugins:
  - jekyll-feed

header_pages:
  - index.md
